// GENERATED by tool/gen_build_info.sh — do not edit by hand.
// Regenerated on every build.

const String kBuildGitShaShort = '5c56d34';
const String kBuildGitShaFull  = '5c56d343b136e4492d7c6506ba962a6d2d5771fa';
const String kBuildCommitSubject = 'fix(mobile): route all Pulse HTTP calls through Settings.yeshieHost()';
const String kBuildTime = '2026-05-11T15:05:03Z';
