// GENERATED by tool/gen_build_info.sh — do not edit by hand.
// Regenerated on every build.

const String kBuildGitShaShort = '6cda299';
const String kBuildGitShaFull  = '6cda299667d8922befd9352d184453724359eceb';
const String kBuildCommitSubject = 'feat(pulse): visible version chip + About page (r7)';
const String kBuildTime = '2026-05-11T18:41:28Z';
