// GENERATED by tool/gen_build_info.sh — do not edit by hand.
// Regenerated on every build.

const String kBuildGitShaShort = 'ad7d16f';
const String kBuildGitShaFull  = 'ad7d16ff822c3fca3b98959e6f8c7f2da82d042e';
const String kBuildCommitSubject = 'fix(pulse): commit R8 working-tree changes — round info, VersionChip, version bump';
const String kBuildTime = '2026-05-12T17:40:08Z';
