// Track A stub — r8 scaffold.
// All producers call appendReminder(); Track A replaces this with the real
// JSONL writer (sr-01). Until then it is a no-op so B/C/D compile cleanly.
//
// Required fields: category, source, title, body.
// Optional: project_tag, link.
// State defaults to 'unread'. id and ts are generated by sr-01.
//
// Record shape (for reference — sr-01 owns the authoritative schema):
//   id           rem-<uuid>
//   ts           ISO8601 UTC
//   category     permission_pending | worker_output | email_bottleneck |
//                self_deferred | dee_question | appointment | health_alert
//   source       producer id string
//   title        one-line string
//   body         markdown ok
//   state        unread (default)
//   snooze_until null
//   project_tag  null or string
//   link         null or deep-link string

// ignore: avoid_unused_parameters
Future<void> appendReminder(Map<String, dynamic> fields) async {
  // no-op until sr-01 lands
}
