#!/usr/bin/env bash
# Generates lib/src/build_info.dart with the current git short SHA, full SHA,
# HEAD commit subject, and build timestamp.
#
# Run from the Pulse repo root BEFORE `flutter build apk` / `flutter build web`.
# Called by the OTA build script.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
OUT="$REPO_ROOT/lib/src/build_info.dart"

SHORT_SHA="$(git rev-parse --short HEAD)"
FULL_SHA="$(git rev-parse HEAD)"
SUBJECT="$(git log -1 --pretty=%s | sed "s/'/\\\\'/g")"
BUILD_TIME="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

mkdir -p "$(dirname "$OUT")"

cat > "$OUT" <<EOF
// GENERATED by tool/gen_build_info.sh — do not edit by hand.
// Regenerated on every build.

const String kBuildGitShaShort = '${SHORT_SHA}';
const String kBuildGitShaFull  = '${FULL_SHA}';
const String kBuildCommitSubject = '${SUBJECT}';
const String kBuildTime = '${BUILD_TIME}';
EOF

echo "wrote $OUT  ($SHORT_SHA  $BUILD_TIME)"
